`timescale 1ns/1ps

module sar_adc #(
    parameter int N = 10
) (
    input  logic         clk,
    input  logic         rst_n,

    // Start a new conversion
    input  logic         start,

    // Comparator output:
    // 1 -> VIN >= VDAC
    // 0 -> VIN <  VDAC
    input  logic         comp_out,

    // Current DAC code generated by the SAR
    output logic [N-1:0] dac_code,

    // Final ADC conversion result
    output logic [N-1:0] adc_code,

    // Conversion status
    output logic         busy,
    output logic         done
);

    typedef enum logic [1:0] {
        IDLE,
        CONVERT,
        DONE
    } state_t;

    state_t state;

    logic [$clog2(N)-1:0] bit_index;

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) begin
            state    <= IDLE;
            bit_index <= '0;
            dac_code <= '0;
            adc_code <= '0;
            busy     <= 1'b0;
            done     <= 1'b0;
        end
        else begin

            case (state)

                // -------------------------------------------------
                // IDLE
                // -------------------------------------------------
                IDLE: begin
                    done <= 1'b0;
                    busy <= 1'b0;

                    if (start) begin

                        // Start from MSB
                        dac_code <= {1'b1, {(N-1){1'b0}}};

                        bit_index <= N-1;

                        busy <= 1'b1;

                        state <= CONVERT;
                    end
                end


                // -------------------------------------------------
                // SAR CONVERSION
                // -------------------------------------------------
                CONVERT: begin

                    // Comparator says VIN >= VDAC
                    // Keep current bit = 1
                    if (comp_out) begin
                        dac_code[bit_index] <= 1'b1;
                    end

                    // Comparator says VIN < VDAC
                    // Clear current bit
                    else begin
                        dac_code[bit_index] <= 1'b0;
                    end


                    // Last bit?
                    if (bit_index == 0) begin

                        // adc_code receives the final SAR result
                        if (comp_out)
                            adc_code <= dac_code | ({{(N-1){1'b0}}, 1'b1} << bit_index);
                        else
                            adc_code <= dac_code & ~({{(N-1){1'b0}}, 1'b1} << bit_index);

                        state <= DONE;

                    end
                    else begin

                        // Move to next lower bit
                        bit_index <= bit_index - 1'b1;

                        // Tentatively set next bit
                        dac_code[bit_index - 1'b1] <= 1'b1;

                    end
                end


                // -------------------------------------------------
                // DONE
                // -------------------------------------------------
                DONE: begin

                    busy <= 1'b0;
                    done <= 1'b1;

                    state <= IDLE;

                end

                default: begin
                    state <= IDLE;
                end

            endcase
        end
    end

endmodule
